export const departments = [
  "Front office",
  "Sales",
  "Finance",
  "Operations",
  "Hiring",
  "Marketing",
] as const;
export type Department = (typeof departments)[number];
export type Automation = {
  id: string;
  title: string;
  department: Department;
  industries: string[];
  hours: [number, number];
  input: string;
  output: string;
  review: string;
};
type Row = [
  string,
  string,
  Department,
  string[],
  number,
  number,
  string,
  string,
];
const rows: Row[] = [
  [
    "after-hours-calls",
    "Answer and book after-hours calls.",
    "Front office",
    ["dental", "automotive", "property-management", "construction"],
    3,
    6,
    "An incoming call outside office hours",
    "An appointment request and a clear summary",
  ],
  [
    "recall-calls",
    "Bring patients back for overdue visits.",
    "Front office",
    ["dental"],
    4,
    7,
    "The list of patients due for a visit",
    "A recall message and a booking link",
  ],
  [
    "insurance-verification",
    "Check insurance before the patient arrives.",
    "Front office",
    ["dental"],
    5,
    8,
    "Patient and appointment details",
    "A coverage checklist for the front desk",
  ],
  [
    "post-op-followups",
    "Follow up after an appointment.",
    "Front office",
    ["dental"],
    2,
    4,
    "The approved aftercare instructions",
    "A scheduled check-in, with concerns flagged",
  ],
  [
    "client-intake",
    "Read the intake form and send it to the right person.",
    "Front office",
    ["legal", "insurance", "staffing", "accounting"],
    3,
    6,
    "A completed client intake form",
    "A client record, missing details, and the next owner",
  ],
  [
    "customer-replies",
    "Draft answers to the questions you hear every day.",
    "Front office",
    [],
    4,
    8,
    "A customer email and your approved information",
    "A reply ready for review",
  ],
  [
    "order-status",
    "Reply to order-status questions.",
    "Front office",
    ["ecommerce", "distribution"],
    5,
    9,
    "A customer question and order details",
    "A reply with the latest order status",
  ],
  [
    "returns",
    "Move return requests to the next step.",
    "Front office",
    ["ecommerce"],
    3,
    5,
    "A return request and your return policy",
    "An eligibility check and next-step instructions",
  ],
  [
    "site-quotes",
    "Draft the quote from site-visit notes.",
    "Sales",
    ["construction"],
    4,
    7,
    "Notes, photos descriptions, and your price list",
    "A draft quote with missing information flagged",
  ],
  [
    "rfq-intake",
    "Turn an RFQ into a ready-to-price job.",
    "Sales",
    ["manufacturing"],
    4,
    7,
    "An emailed request for quote",
    "Part quantities, specifications, and due dates",
  ],
  [
    "quote-followups",
    "Follow up on quotes before they go cold.",
    "Sales",
    ["construction", "automotive", "manufacturing", "distribution"],
    3,
    6,
    "Open quotes and the last customer response",
    "A timed follow-up ready to send",
  ],
  [
    "call-notes",
    "Put customer call notes in the right record.",
    "Sales",
    [],
    3,
    5,
    "A call transcript you provide with permission",
    "A summary, next steps, and a customer record update",
  ],
  [
    "lead-routing",
    "Get each new lead to the right person.",
    "Sales",
    ["marketing", "insurance", "automotive"],
    2,
    4,
    "An incoming inquiry",
    "An assigned owner and a suggested next action",
  ],
  [
    "renewal-reminders",
    "Start renewals before the last-minute rush.",
    "Sales",
    ["insurance", "property-management"],
    3,
    5,
    "Upcoming renewal dates",
    "A reminder schedule and draft customer messages",
  ],
  [
    "service-reminders",
    "Remind customers when service is due.",
    "Sales",
    ["automotive"],
    3,
    5,
    "Service history and an approved reminder schedule",
    "A timely message with booking instructions",
  ],
  [
    "unpaid-invoices",
    "Chase unpaid invoices on a schedule.",
    "Finance",
    [],
    3,
    6,
    "An aging report and your payment terms",
    "A sequence of polite reminders, paused when paid",
  ],
  [
    "invoice-coding",
    "Read invoices and draft the bookkeeping entries.",
    "Finance",
    ["accounting", "construction", "distribution"],
    4,
    7,
    "Supplier invoices and your account categories",
    "Proposed entries and exceptions for review",
  ],
  [
    "receipt-matching",
    "Match receipts to the expense record.",
    "Finance",
    [],
    2,
    4,
    "Receipts and the expense list",
    "Suggested matches, with gaps flagged",
  ],
  [
    "timesheet-reminders",
    "Get timesheets in before payroll.",
    "Finance",
    ["staffing", "construction", "manufacturing"],
    2,
    4,
    "The missing-timesheet list",
    "Reminders and an updated completion list",
  ],
  [
    "billing-notes",
    "Turn job notes into a draft invoice.",
    "Finance",
    ["legal", "construction", "automotive"],
    3,
    6,
    "Approved work notes and billing rates",
    "An itemized invoice draft",
  ],
  [
    "document-chasing",
    "Collect client documents without the email chase.",
    "Finance",
    ["accounting", "legal", "insurance"],
    4,
    8,
    "A required-document checklist",
    "Targeted reminders for the items still missing",
  ],
  [
    "purchase-orders",
    "Turn a supplier email into a purchase order.",
    "Operations",
    ["distribution", "manufacturing", "automotive"],
    4,
    7,
    "An order email and your product list",
    "A purchase order draft with quantities and prices",
  ],
  [
    "maintenance-routing",
    "Send repair requests to the right contractor.",
    "Operations",
    ["property-management"],
    4,
    7,
    "A tenant repair request",
    "A categorized work order and assigned contractor",
  ],
  [
    "material-certs",
    "Match material certs to the right job.",
    "Operations",
    ["manufacturing"],
    2,
    4,
    "A material certificate and job references",
    "A filed certificate and any missing references",
  ],
  [
    "job-travelers",
    "Get job paperwork ready for the shop floor.",
    "Operations",
    ["manufacturing"],
    3,
    6,
    "An approved order and shop instructions",
    "A job traveler draft with the required steps",
  ],
  [
    "supplier-updates",
    "Follow up with suppliers on late orders.",
    "Operations",
    ["distribution", "manufacturing", "construction"],
    3,
    5,
    "Open purchase orders and promised dates",
    "Status requests and a list of delivery risks",
  ],
  [
    "delivery-updates",
    "Tell customers when their delivery changes.",
    "Operations",
    ["distribution", "ecommerce"],
    2,
    4,
    "Updated delivery information",
    "A clear customer update",
  ],
  [
    "inventory-alerts",
    "Flag stock that needs attention.",
    "Operations",
    ["ecommerce", "distribution", "automotive"],
    2,
    4,
    "Stock levels and approved reorder thresholds",
    "A reorder list with exceptions highlighted",
  ],
  [
    "job-scheduling",
    "Turn the approved job into a scheduling request.",
    "Operations",
    ["construction", "automotive"],
    3,
    5,
    "Job details and crew availability",
    "A proposed schedule for your approval",
  ],
  [
    "deadline-reminders",
    "Keep deadlines out of one person’s head.",
    "Operations",
    ["accounting", "legal", "insurance"],
    2,
    4,
    "A list of due dates and owners",
    "Timely reminders and overdue exceptions",
  ],
  [
    "candidate-intake",
    "Organize candidate details without retyping.",
    "Hiring",
    ["staffing"],
    3,
    6,
    "A résumé and candidate-provided information",
    "A factual candidate record for a human recruiter",
  ],
  [
    "interview-scheduling",
    "Book interviews without the back-and-forth.",
    "Hiring",
    ["staffing"],
    4,
    7,
    "Agreed interviewers and available times",
    "An invitation and a clear interview schedule",
  ],
  [
    "onboarding-checklists",
    "Keep new-hire paperwork moving.",
    "Hiring",
    [],
    2,
    4,
    "Your approved onboarding checklist",
    "Requests and reminders for missing documents",
  ],
  [
    "applicant-updates",
    "Keep applicants informed as things move.",
    "Hiring",
    ["staffing"],
    2,
    4,
    "A hiring-stage update from your team",
    "An approved candidate update",
  ],
  [
    "training-reminders",
    "Remind people about required training.",
    "Hiring",
    ["manufacturing", "construction", "dental"],
    1,
    3,
    "Training requirements and completion dates",
    "A reminder list for staff and managers",
  ],
  [
    "client-reports",
    "Build the weekly client report.",
    "Marketing",
    ["marketing"],
    4,
    7,
    "Your reporting exports and reporting format",
    "A draft report with figures linked to their source",
  ],
  [
    "approval-reminders",
    "Follow up on work waiting for approval.",
    "Marketing",
    ["marketing", "construction"],
    2,
    4,
    "Pending work and the named approver",
    "A reminder with the item that needs a decision",
  ],
  [
    "review-requests",
    "Ask for a review after a completed job.",
    "Marketing",
    ["automotive", "construction", "dental"],
    1,
    3,
    "Completed jobs and your approved request text",
    "A scheduled review request to eligible customers",
  ],
  [
    "content-repurposing",
    "Turn approved notes into a first draft.",
    "Marketing",
    ["marketing", "ecommerce"],
    2,
    5,
    "Your approved material and writing guidance",
    "A draft for a person to check before publishing",
  ],
  [
    "certificate-requests",
    "Prepare certificate requests for review.",
    "Front office",
    ["insurance"],
    2,
    4,
    "A customer request and policy information",
    "A populated request with missing details flagged",
  ],
];
export const automations: Automation[] = rows.map(
  ([id, title, department, industries, low, high, input, output]) => ({
    id,
    title,
    department,
    industries,
    hours: [low, high],
    input,
    output,
    review:
      "Your team checks exceptions and approves anything that needs a decision.",
  }),
);
// The first view spans a real working week across departments and businesses.
export const featuredAutomationIds = [
  "after-hours-calls",
  "unpaid-invoices",
  "purchase-orders",
  "site-quotes",
  "client-intake",
  "call-notes",
  "document-chasing",
  "interview-scheduling",
  "client-reports",
];
export const estimateNote =
  "Illustrative weekly estimates for recurring work. Actual time varies by volume and process. Overlapping tasks should not be added together.";
