// Static interface copy. Business offers and industry facts have their own content files.
export const interfaceCopy = {
  Booking: {
    "3": " / 3",
    within_a_month: "Within a month",
    inline: "Inline",
    not_provided: "Not provided",
    a_conversation_not_a_commitment: " A conversation, not a commitment.",
    "30_minutes": "30 minutes",
    tell_us_what: "Tell us what",
    keeps_coming: "keeps coming",
    back_to_your_desk: "back to your desk.",
    youll_talk_to_the_person_who:
      "You’ll talk to the person who does the building.",
    well_start_with_your_week_and:
      "We’ll start with your week and work out whether",
    the_audit_is_a_useful_next: " the Business Tune-Up is a useful next step.",
    thirty_minutes_focused_on_your_business:
      " Thirty minutes, focused on your business.",
    no_obligation_to_buy_an_audit: " No obligation to buy a Tune-Up.",
    clear_scope_published_prices: " Clear scope. Published prices.",
    your_first_conversation: " Your first conversation",
    throughline_ai: "Digital Handyman",
    company_name: "Company name ",
    optional: "optional",
    your_company: "Your company",
    what_is_eating_the_most_time: "What is eating the most time? ",
    we_spend_every_friday_chasing_invoices:
      "We spend every Friday chasing invoices…",
    choose_a_time_for_your_30minute: "Choose a time for your 30-minute call",
    lets_make_time_for_better_work: "Let’s make time for better work.",
    online_scheduling_is_not_available_yet:
      "Online scheduling is not available yet.",
    save_your_call_agenda_to_have: "Save your call agenda to have it ready.",
    discuss_recurring_work_and_possible_starting:
      "Discuss recurring work and possible starting points.",
    save_my_call_agenda: "Save my call agenda",
    request_a_call_by_email: "Request a call by email",
    prefer_to_put_it_in_writing: "Prefer to put it in writing?",
    send_me_a_written_quote_instead: "Send me a written quote instead",
    close_quote_request: "Close quote request",
    what_would_you_like_taken_care: "What would you like taken care of?",
    when_would_you_like_to_start: "When would you like to start?",
    what_budget_are_you_working_with: "What budget are you working with?",
    your_quote_request_has_been_sent: "Your quote request has been sent.",
    your_request_has_not_been_sent:
      "Your request has not been sent. Save a copy and try again later.",
    the_work: "The work",
    choose_a_starting_point: "Choose a starting point",
    help_me_find_the_right_starting: "Help me find the right starting point.",
    choose_a_timeline: "Choose a timeline",
    within_three_months: "Within three months",
    approximate_budget: "Approximate budget",
    text: " — ",
    "2500_start_with_an_audit": "$2,500 — start with a Business Tune-Up",
    id_like_guidance_on_scope: "I’d like guidance on scope.",
    your_email: "Your email",
    youyourcompanycom: "you@yourcompany.com",
    go_back: "Go back",
    sending: "Sending…",
    continue: "Continue",
    send_quote_request: "Send quote request",
    save_a_copy_of_my_request: "Save a copy of my request",
  },
  Calculator: {
    "2500": "$2,500",
    "9500": "$9,500",
    put_a_number_on_your_time: " Put a number on your time.",
    your_assumptions_your_estimate: "Your assumptions. Your estimate.",
    what_is_the: "What is the",
    busywork_costing: "busywork costing?",
    a_few_hours_across_a_few: "A few hours across a few people add up.",
    move_the_numbers_to_match_your: "Move the numbers to match your business.",
    people_doing_the_work: "People doing the work",
    hours_each_spends_per_week: "Hours each spends per week",
    hourly_cost_including_overhead: "Hourly cost, including overhead",
    share_that_could_be_automated: "Share that could be handled automatically",
    estimated_value_of_time_recovered_per:
      "Estimated value of time recovered, per year",
    hours_back_every_week: " hours back every week",
    recovered_time_year: "Recovered time / year",
    automation_audit: "Business Tune-Up",
    build_sprint_starting_at: "Get-It-Done Build, starting at",
    months: " months",
    of_recovered_time_equals_the_starting:
      "of recovered time equals the starting Sprint price.",
    estimated_capacity_not_guaranteed_cash_savings:
      "Estimated capacity, not guaranteed cash savings. Based on 52 weeks. Software and ongoing support costs are additional. We check the real numbers in your Business Tune-Up.",
  },
  Demo: {
    "4000": " / 4,000",
    try_a_sample_message_to_continue: "Try a sample message to continue.",
    dont_take_our_word_for_it: " Don’t take our word for it.",
    see_the_work_happen: " See the work happen",
    messy_in: "Messy in.",
    ready_to_work_with: "Ready to work with.",
    a_customer_email_a_supplier_invoice:
      "A customer email. A supplier invoice. Notes from a job.",
    see_what_happens_when_the_retyping:
      "See what happens when the retyping goes away.",
    what_arrived: " What arrived",
    your_inbox_on_a_normal_day: "Your inbox, on a normal day",
    paste_a_customer_message_or_choose:
      "Paste a customer message or choose a sample",
    working_on_it: "Working on it…",
    see_it_organized: "See it organized",
    ready_for_the_next_step: " Ready for the next step",
    processing: "Processing",
    sample_replay: "Sample replay",
    live_result: "Live result",
    awaiting_your_message: "Awaiting your message",
    result_view: "Result view",
    the_details: "The details",
    draft_reply: "Draft reply",
    reading_the_message_and_checking_the:
      "Reading the message and checking the details.",
    select_the_draft_text_to_copy: "Select the draft text to copy it.",
    copied: "Copied",
    copy_draft: "Copy draft",
    a_draft_for_your_team_to: "A draft for your team to review before sending.",
    the_useful_part_without_the_retyping:
      "The useful part. Without the retyping.",
    run_the_example_or_paste_a:
      "Run the example or paste a message to see the details, next steps, and a drafted reply.",
    or_try_a_familiar_example: "Or try a familiar example",
    this_is_a_recorded_sample_not:
      "This is a recorded sample, not a live reading of your message.",
    use_a_sample_or_remove_private:
      "Use a sample or remove private details before trying your own message. Nothing is sent, booked, or changed by this demo.",
  },
  EmailCopy: {
    email_me_this_estimate: "Email me this estimate",
    your_copy_is_on_its_way: "Your copy is on its way.",
    your_email_has_not_been_sent:
      "Your email has not been sent. Download your copy instead.",
    youyourcompanycom: "you@yourcompany.com",
    sending: "Sending…",
    send_copy: "Send copy",
    your_estimate_is_yours_no_email:
      "Your estimate is yours. No email required to see it.",
    save_a_copy_of_your_estimate: "Save a copy of your estimate",
    save_a_copy: " Save a copy",
  },
  GlobalControls: {
    what_we_automate: "What we fix",
    how_it_works: "How it works",
    try_the_demo: "Try the demo",
    calculate_your_time: "Calculate your time",
    find_your_starting_point: "Find your starting point",
    pricing: "Pricing",
    meet_the_studio: "The studio",
    book_a_call: "Book a call",
    go_to: "Go to",
    automation: "Time-saver",
    throughline_ai_home: "Digital Handyman home",
    main_navigation: "Main navigation",
    who_we_are: "Our approach",
    search_the_website: "Search the website",
    k: "⌘ K",
    close_navigation: "Close navigation",
    open_navigation: "Open navigation",
    your_industry: "Your industry",
    choose_your_industry: "Choose your industry",
    call_throughline_ai: "Call Digital Handyman",
    arrowdown: "ArrowDown",
    arrowup: "ArrowUp",
    enter: "Enter",
    find_a_task_or_jump_to: "Find a task or jump to a section…",
    search_tasks_and_sections: "Search tasks and sections",
    close_search: "Close search",
    esc: "esc",
    search_results: "Search results",
    no_matching_work_try_invoice_or:
      "No matching work. Try “invoice” or “call”.",
    use_to_choose_enter_to_open: "Use ↑ ↓ to choose. Enter to open.",
    close_suggestion: "Close suggestion",
    leave_with_a: "Leave with a",
    starting_point: "starting point.",
    eight_questions_about_your_week_three:
      "Eight questions about your week. Three tasks worth looking at. Your results appear right away.",
    find_my_starting_point: "Find my starting point",
    keep_exploring: "Keep exploring",
    book_a_30minute_call: "Book a 30-minute call",
    see_what_wed_automate: "See what we can take care of",
  },
  Icon: {
    throughline_ai: "Digital Handyman",
    throughline: "digital handyman",
    ai: "",
  },
  Landing: {
    "10": "10",
    "2500": "$2,500",
    the_work_as_it_arrives: " The work, as it arrives",
    a_little_more_order: " A little more order",
    built_for_your_business: "Built around the way you work.",
    made_for_the_way_your_business: "Made for the way your business works.",
    a_clear_place_to_start: "A clear place to start",
    automation_audit: "Business Tune-Up ",
    one_week_credited_in_full_toward:
      "One week. Credited in full toward any build.",
    scroll_to_the_automation_library: "Scroll to the ways we can help",
    keep_exploring: "Keep exploring",
    the_work_is_obvious_the_way: " The work is obvious. The way out isn’t.",
    youve_probably: "You’ve probably",
    tried_to_fix_this: "tried to fix this.",
    text: "+",
    you_should_know_what_this_costs: " You should know what this costs.",
    a_scope_a_price_something_that: "A scope. A price. Something that works.",
    no_openended: "No open-ended",
    lets_explore_ai: "“maybe the computer can do it.”",
    start_with_the_audit_know_what:
      "Start with the Tune-Up. Know what is worth fixing.",
    then_decide_what_happens_next: "Then decide what happens next.",
    the_work: "The work",
    what_you_get: "What you get",
    your_investment: "Your investment",
    start_here: " Start here",
    talk_about_the_audit: "Talk about the Tune-Up",
    book_a_call: "Book a call",
    ten_hours_a_week_or_theres: "Ten hours a week. Or there’s no charge.",
    hrs: "hrs",
    precision_is_a_habit: "Built around your work.",
    studio_caption:
      "From the first walkthrough to the handoff.",
    studio_eyebrow: "The Digital Handyman way.",
    your_automation: "Built for your work.",
    studio_headline_second: "Ready for your team.",
    studio_headline_third: "Yours to keep.",
    studio_lead:
      "A useful fix starts with understanding an ordinary day in your business.",
    studio_scope:
      "We start with the files, calls, and follow-ups your team handles every week. Then we agree on one useful change, a clear scope, and a price before the build begins.",
    studio_review:
      "Your team reviews the result against real work. We check what happens when details are missing, requests change, or someone needs to step in.",
    studio_handoff:
      "You get the finished work, practical documentation, and training for the people who will use it. It runs in accounts you control.",
    studio_commitment: "Clear scope. Careful delivery. Your ownership.",
    in_their_own_words: "In their own words.",
    text_1: ", ",
    care_in_every_detail: " Care in every detail.",
    throughline_ai_home: "Digital Handyman home",
    less_busywork: "Less busywork.",
    more_room_for_your_business: "More room for your business.",
    the_prices: "The prices",
    the_short_version: "The short version",
    lets_talk: "Let’s talk",
    made_for_the_work_in_your: "Made for the work in your business.",
    throughline: "digital handyman",
    ai: "",
    text_2: "© ",
    throughline_ai: " Digital Handyman",
    built_with_care_built_to_be: "Built with care. Built to be yours.",
    privacy: "Privacy",
  },
  Library: {
    all_work: "All work",
    familiar_work_a_different_way_to:
      " Familiar work. A different way to do it.",
    possibilities: " possibilities",
    find_your: "Find your",
    every_single_week: "“every single week.”",
    the_calls_the_chasing_the_copying:
      "The calls. The chasing. The copying and pasting.",
    start_with_something_you_wish_would:
      "Start with something you wish would just get done.",
    filter_by_department: "Filter by department",
    search_automations: "Search ways we can help",
    find_a_task: "Find a task",
    filter_by_industry: "Filter by industry",
    every_industry: "Every industry",
    text: "–",
    hrs_week: "hrs / week",
    what_comes_in: "What comes in",
    what_gets_done: "What gets done",
    book_a_call_about_this: "Book a call about this",
    no_matching_tasks_yet: "No matching tasks yet.",
    try_a_broader_search_or_choose:
      "Try a broader search or choose another department.",
    show_all_work: "Show all work",
    show_fewer_tasks: "Show fewer tasks",
  },
  Scorecard: {
    "8": "8",
    "100": "/ 100",
    a_useful_place_to_start: " A useful place to start.",
    not_sure_what: "Not sure what",
    to_automate: "to fix first?",
    start_here: "Start here.",
    eight_questions_about_an_ordinary_week:
      "Eight questions about an ordinary week.",
    three_places_you_could_get_time: "Three places you could get time back.",
    about_two_minutes_results_right_away:
      " About two minutes. Results right away.",
    quotes_followups: "Quotes & follow-ups",
    invoices_paperwork: "Invoices & paperwork",
    calls_customer_requests: "Calls & customer requests",
    the_work_only_you_know: "The work only you know",
    a_clearer_picture_of_your_week: "A clearer picture of your week.",
    no_email_gate_no_technical_questions:
      "No email gate. No technical questions.",
    just_the_work_your_team_knows: "Just the work your team knows too well.",
    find_my_starting_point: "Find my starting point",
    your_automation_opportunity_score: "Your time-saving opportunity score",
    there_is_room_to_get_time: "There is room to get time back.",
    you_already_have_a_good_head: "You already have a good head start.",
    these_are_three_starting_points_to:
      "These are three starting points to check in a Business Tune-Up.",
    these_are_areas_to_check_rather:
      "These are areas to check, rather than assume they need a build.",
    text: "–",
    h: "h",
    up_to_roughly: "Up to roughly ",
    hours_per_week_at_the_low:
      " hours per week at the low end of these task estimates, before checking overlap and your actual volume. This score measures repeated manual work, not a promise of savings.",
    talk_about_my_starting_point: "Talk about my starting point",
    start_again: "Start again",
    about_your_week: "About your week",
    text_1: " / ",
    previous_question: "Previous question",
    choose_what_happens_most_often: "Choose what happens most often.",
  },
  StageFlow: {
    from_the_first_call_to_your: " From the first call to your team",
    a_clear_beginning_a_proper_handoff: "A clear beginning. A proper handoff.",
    less_talk_about_ai: "Less talk about technology.",
    more_work_off_your_plate: "More work off your plate.",
    we_start_small_put_a_number: "We start small, put a number on it,",
    and_build_something_your_team_can:
      " and build something your team can use.",
    a_supplier_email: "A supplier email",
    details_scattered_across_your_inbox: "Details scattered across your inbox.",
    a_purchase_order: "A purchase order",
    ready_for_your_team_to_review: "Ready for your team to review.",
  },
  app_call_page: {
    the_short_version_ai_automation_for:
      "The short version: practical digital help for your business, with clear prices and a ten-hour guarantee.",
    explore_the_full_site: "Explore the full site",
    for_owners_and_teams_with_too:
      "For owners and teams with too much repeat work.",
    a_clearer_week: "A clearer week",
    starts_with_a_conversation: "starts with a conversation.",
    the_2500_audit_fee_is_credited:
      " The $2,500 Tune-Up fee is credited in full against any build.",
    book_a_30minute_call: "Book a 30-minute call",
    throughline_business_tagline:
      "Digital Handyman. Modern tools. Old-fashioned follow-through.",
  },
  app_privacy_page: {
    privacy: "Privacy",
    a_clear_note_on_privacy: "A clear note on privacy.",
    the_calculator_and_scorecard_run_in:
      "The calculator and scorecard run in your browser. Campaign information and your selected starting point are kept in session storage for this visit. This site does not use local storage.",
    trying_the_demo: "Trying the demo",
    when_live_processing_is_connected_the:
      "When live processing is connected, the message you submit is sent to our processing provider to produce the result. Avoid private, sensitive, or confidential information. Sample playback is labeled and does not process your own message. Demo inputs are not stored by this application; provider retention terms apply to live processing.",
    booking_and_email: "Booking and email",
    when_you_open_the_calendar_the:
      "When you open the calendar, the scheduling provider receives your booking details, campaign information, and the preparation details you provide. Email copies and written quote requests use an email delivery provider when configured. Downloading a copy works in your browser.",
    measurement: "Measurement",
    the_site_records_meaningful_interaction_events:
      "The site records meaningful interaction events without including your demo input. No external analytics provider is connected by default. A session-scoped campaign record helps prepare the call.",
    your_details: "Your details",
    contact_details_will_be_published_before:
      "Contact details will be published before online booking and email delivery open.",
    back_to_throughline_ai: "Back to Digital Handyman",
  },
} as const;
